# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id_items', models.IntegerField(max_length=7, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('copies', models.CharField(max_length=100)),
                ('id_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Perpustakaan')),
            ],
        ),
    ]
