# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjam',
            name='fee',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='peminjam',
            name='return_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
