# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_auto_20210525_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjam',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peminjam',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
